import { StyleSheet } from 'react-native'

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:"#e0e0e0",
    },
    image:{
        padding:10,
        margin:10,
        alignItems:"center",
        flex:10,
    },
    after_image:{
        padding:10,
        margin:10,
        flex:6,
    },
    title:{
        fontSize:30,
        fontWeight:"bold",
        color:"black",
    },
    description:{
        fontSize:17,
        fontWeight:"500",
        color:"black",
    },
    price_box:{
        flexDirection:"row",
        
        backgroundColor:"white",
        borderWidth:1,
        borderColor:"#e0e0e0",
        flex:2,
        
    },
    price_inner_box:{
        flexDirection:"row",
        alignItems:"center",
        flex:1,
        padding:10,
        justifyContent:"space-between",
    },
    price:{
        fontSize:20,
        fontWeight:"bold",
        marginLeft:15,
        color:"#ff9800",
    },
    cart:{
        backgroundColor:"white",
        justifyContent:"center",
        borderRadius:20,
        flexDirection:"row",
        padding:5,
    },
    cart_text:{
        fontSize:22,
        fontWeight:"500",
        color:"orange",
    }
})